language: php

sudo: false

php:
  - 7.2
  - 7.3
  - 7.4

env:
  global:
    - DEFAULT=1

matrix:
  fast_finish: true

  include:
    - php: 7.2
      env: CODECOVERAGE=1 DEFAULT=0

    - php: 7.2
      env: CHECKS=1 DEFAULT=0

before_install:
  - phpenv config-rm xdebug.ini

before_script:
  - if [[ $PREFER_LOWEST != 1 ]]; then composer install --prefer-source --no-interaction; fi
  - if [[ $PREFER_LOWEST == 1 ]]; then composer update --prefer-lowest --prefer-stable --prefer-dist --no-interaction; fi

script:
  - if [[ $DEFAULT == 1 ]]; then vendor/bin/phpunit; fi
  - if [[ $CHECKS == 1 ]]; then composer phpstan-setup && composer phpstan; fi
  - if [[ $CHECKS == 1 ]]; then composer cs-setup && composer cs-check; fi
  - if [[ $CODECOVERAGE == 1 ]]; then phpdbg -qrr vendor/bin/phpunit --coverage-clover=clover.xml; fi

after_success:
  - if [[ $CODECOVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

cache:
  directories:
    - $HOME/.composer/cache

notifications:
  email: false